src/objects/Case_Study__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Case Study</label>
    <nameField>
        <displayFormat>CS-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Case Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LTNG_CaseStudyAuraCtrl.cls
public class LTNG_CaseStudyAuraCtrl {
	DB_CaseStudySelector caseStudySelector;
	
	LTNG_CaseStudyAuraCtrl(DB_CaseStudySelector caseStudySelector) {
		this.caseStudySelector = caseStudySelector;
	}

	LTNG_CaseStudyAuraCtrl() {
		this(new DB_CaseStudySelector());
	} 
	
	@AuraEnabled
	public static String getCaseStudyName (String recordId) {
		return (new LTNG_CaseStudyAuraCtrl()).selectCaseStudyName((Id) recordId);
	}
	
	private String selectCaseStudyName (Id caseStudyId) {
		Set<Id> caseStudyIdSet = new Set<Id>{caseStudyId};
		List<Case_Study__c> caseStudyList = (List<Case_Study__c>) this.caseStudySelector.selectSObjectsById(caseStudyIdSet);
		return caseStudyList[0].name__c; 
	}
}