src/objects/Case_Study__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Case Study</label>
    <nameField>
        <displayFormat>CS-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Case Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_User__c.object
<CustomObject>
    <fields>
        <fullName>Case_Study__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Study</label>
        <referenceTo>Case_Study__c</referenceTo>
        <relationshipLabel>Test Users</relationshipLabel>
        <relationshipName>Test_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Test User</label>
    <nameField>
        <displayFormat>TU-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Test User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LTNG_TestUserAuraCtrl.cls
public class LTNG_TestUserAuraCtrl {
	DB_GenericDml genericDml;
	
	LTNG_TestUserAuraCtrl(DB_GenericDml genericDml) {
		this.genericDml = genericDml;
	}

	LTNG_TestUserAuraCtrl() {
		this(new DB_GenericDml());
	} 
	
	@AuraEnabled
	public static Test_User__c saveUser (String name, String password, String email, String nickname, String caseStudyId) {
		return (new LTNG_TestUserAuraCtrl()).saveUser(new Test_User__c (
			Name__c = name, 
			Password__c = password, 
			Email__c = email, 
			Nickname__c = nickname, 
			Case_Study__c = caseStudyId
		));
	}
	
	public Test_User__c saveUser (Test_User__c testUser) {
		this.genericDml.doUpsert(new List<Test_User__c>{testUser}); 
		return testUser;
	}
}