src/objects/Case_Study__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Case Study</label>
    <nameField>
        <displayFormat>CS-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Case Study Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DB_CaseStudySelector.cls
public class DB_CaseStudySelector extends fflib_SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Case_Study__c.name__c 
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Case_Study__c.sObjectType;
    }

    public List<Case_Study__c> selectById(Set<Id> idSet) {
   		return (List<Case_Study__c>) selectSObjectsById(idSet);
    }
}